"""This module models the brake force exerted by the friction pad"""

# Used to avoid no-self-use error for compute
# pylint: disable=R0201

from openmdao.api import ExplicitComponent  # pylint: disable=import-error


class BrakeForce(ExplicitComponent):
    """Class to measure the brake force generated by the brake pads"""

    def initialize(self):
        """Declare options"""
        #

    def setup(self):
        """Declare inputs and outputs"""
        self.add_input('FrictionCoefficient',
                       1.,
                       desc="Coefficient of friction of the friction pad.")
        self.add_input('NormalForce',
                       1.,
                       desc="Normal Force applied to the friction pad.")
        self.add_output('FrictionForce',
                        0.45,
                        desc="Friction Force generated by the friction pad")
        self.add_input('SurfaceVelocity',
                       1.,
                       desc="Velocity of the friction pad.")
        self.add_input('Temperature',
                       1.,
                       desc="Temperature of the friction pad.")

    def compute(self,
                inputs,
                outputs):
        """Compute outputs"""
        c_f = inputs["FrictionCoefficient"]
        normal_force = inputs["NormalForce"]
        friction_force = c_f * normal_force
        outputs["FrictionForce"] = friction_force
